---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  tasks:
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/install-tools"
      
